name: Automatically send Issues to the project
on:
  issues:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: srggrs/assign-one-project-github-action@@1.3.1 
        with:
          project: 'https://github.com/mokocm/diet/projects/1'
          column_name: 'WIP'
