name: Open daily eat report issue
on:
  schedule:
    - cron: 5 0 * * *

jobs:
  create_new_issue:
    name: Create a new eat report issue.
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create new eat report issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          labels: "Eat Report"
          title: "YYYY/MM/DD 食事レポート"
          body: |
            |name|kcal|
            |-----|---|
            |昼ご飯|kcal|
            |夜ご飯|kcal|
            ||kcal|

            ref: #
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create new workout report issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          labels: "Eat Report"
          title: "YYYY/MM/DD 運動レポート"
          body: |
            TBD
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}